<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="gbibc-dv00-17-v" name="com.ics.tests.fred.Sprint3_3" tests="1" failures="0" timestamp="16 Feb 2017 17:02:12 GMT" time="0.005" errors="1">
  <testcase name="test_case_62949" time="0.005" classname="com.ics.tests.fred.Sprint3_3">
    <error type="java.io.FileNotFoundException" message="File &#039;C:\Users\NatarajD\Desktop\05MF01_Image.sql&#039; does not exist">
      <![CDATA[java.io.FileNotFoundException: File 'C:\Users\NatarajD\Desktop\05MF01_Image.sql' does not exist
	at org.apache.commons.io.FileUtils.openInputStream(FileUtils.java:299)
	at org.apache.commons.io.FileUtils.readFileToString(FileUtils.java:1711)
	at org.apache.commons.io.FileUtils.readFileToString(FileUtils.java:1748)
	at com.ics.seleniumCoreUtilis.WebDriverAndJavaUtilis.readDataOfFileStream(WebDriverAndJavaUtilis.java:39)
	at com.ics.externalFactoryUtilis.ICSDBUtilis.createSQLFileFromTemplate(ICSDBUtilis.java:26)
	at com.ics.fred.testScenarios.SingleFileInsertionCreditItem.generateAndVerifyX9FileName(SingleFileInsertionCreditItem.java:13)
	at com.ics.tests.fred.Sprint3_3.test_case_62949(Sprint3_3.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </error>
  </testcase> <!-- test_case_62949 -->
</testsuite> <!-- com.ics.tests.fred.Sprint3_3 -->
